<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\Icons\logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\Icons\logo.ico" />
    <None Remove="Assets\Icons\logo.png" />
    <None Remove="Assets\Icons\open_eye.png" />
  </ItemGroup>

  <ItemGroup>
    <DesignDataWithDesignTimeCreatableTypes Include="Assets\Icons\logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\" />
    <Folder Include="Resources\" />
    <Folder Include="Models\" />
    <Folder Include="ViewModels\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.3.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.1" />
    <PackageReference Include="Microsoft.Office.Interop.Excel" Version="15.0.4795.1001" />
    <PackageReference Include="Ookii.Dialogs.Wpf" Version="5.0.1" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.5" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Icons\logo.ico" />
    <Resource Include="Assets\Icons\logo.png" />
    <Resource Include="Assets\Icons\open_eye.png" />
  </ItemGroup>

</Project>
